steps:
  - name: "golang:1.22"
    args: ["go", "get", "-d", "./..."]
    env:
      - "GO_VERSION=1.22"
      - "GOPATH=/gopath"
    volumes:
      - name: "go"
        path: "/gopath"
  - name: "golang:1.22"
    args: ["go", "build", "-o", "main", "."]
    env:
      - "GO_VERSION=1.22"
      - "GOPATH=/gopath"
    volumes:
      - name: "go"
        path: "/gopath"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    timeout: "1600s"
    env:
      - "GO_VERSION=1.22"
      - "GOPATH=/gopath"
    volumes:
      - name: "go"
        path: "/gopath"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
        versions=$(gcloud app versions list --service web-log --sort-by '~version' --format 'value(VERSION.ID)' | tail -n +11)
        if [ -n "$versions" ]; then
          echo "Deleting old versions: $versions"
          for version in $versions; do
            gcloud app versions delete $version --service web-log --quiet || echo "Error deleting version: $version"
          done
        else
          echo "No old versions to delete"
        fi
options:
  logging: CLOUD_LOGGING_ONLY
